# Site settings
title: Vipin's Blog
default_author: Vipin Sharma
description: "Vipin's Blog"  # used in site head

# register on google analytics and replace this token
google_analytics: UA-139438802-1
# disque comments are broken if you send http:// along with url, this url is same as the one given on disqus
# Deleting the value would remove it from footer.
disqus_url: vipinsharma85@gmail.com
disqus_id: vipinsharma85
# register on feedburner and replace this url. Deleting the value will remove it from footer.
feedburner_url: https://feedburner.google.com/fb/a/mailverify?uri=programmer-wannabe&amp;loc=en_US

# footer details. Deleting the value would remove it from footer.
github_username:  Vipin-Sharma
facebook_username:
email: vipinsharma85@gmail.com
stackoverflow_username: 2922515
twitter_username : vipinbit85
linkedin_username : vipinsharma85
keybase_username :
copyright_name: Vipin Sharma
rss : false

# used for portfolio on home page
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: blog/page:num

# gem dependencies
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]
